---
# file: monitor the installation progress and config the nodes

- name: Update inventory to have all hosts defined in vars.yaml
  hosts: bastion
  gather_facts: no
  any_errors_fatal: true
  roles:
  - update-inventory

- name: Run ocp4-playbooks to install OCP
  import_playbook: ocp4-playbooks/playbooks/install-compete.yaml



